[api]
key = "d6c344842e93593e7042c12b00dc4ba5df4c196f"

[project]
name = "TODOs-todoist-sync"
src_folder = "TODOs-todoist-sync"
keywords = [ "DEBUG:", "NOTE:", "HACK:", "TODO:", "DECIDE:", "FIXME:", "REFACTOR:",]
filetypes = ".py"
todoist_id = 2195030298
